# 📌 Requisitos Funcionais

| Código | Função                                | Descrição                                                                                                                                                     | Ator                                |
|--------|---------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------|
| RF001  | Manter Usuário                        | Permitir o cadastro de usuários com nome, login, senha, telefone e tipo (admin, gerente, caixa, estoquista). Status, acesso.                                   | Administrador                       |
| RF002  | Autenticar login                      | Permitir que o usuário se autentique com login e senha.                                                                                                        | Todos os usuários                   |
| RF003  | Alterar Senha                         | Permitir que o usuário altere sua senha.                                                                                                                       | Todos os usuários                   |
| RF004  | Manter Categoria                      | Permitir cadastrar categorias de produtos com nome, descrição, alteração ou exclusão.                                                                          | Administrador, Gerente              |
| RF005  | Manter Produto                        | Permitir o cadastro de produtos com dados como nome, descrição, preço, categoria, estoque mínimo, ativar ou desativar produtos no sistema.                     | Gerente, Estoquista                  |
| RF006  | Consultar Produtos                    | Listar todos os produtos com filtros por nome, categoria, ativo/inativo.                                                                                       | Todos os usuários                   |
| RF007  | Manter Fornecedor                     | Permitir o cadastro de fornecedores com dados completos, editar ou excluir fornecedores cadastrados.                                                           | Gerente                             |
| RF008  | Manter Compra                         | Permitir registrar compras com fornecedor, forma de pagamento, nota fiscal e status.                                                                           | Gerente, Estoquista                  |
| RF009  | Registrar Itens da Compra             | Permitir adicionar produtos à compra com quantidade, preço e validade.                                                                                         | Estoquista                          |
| RF010  | Atualizar Estoque na Compra           | Atualizar automaticamente o estoque ao finalizar uma compra.                                                                                                   | Sistema                             |
| RF011  | Controlar Estoque                     | Registrar e exibir a quantidade atual, última entrada e saída de cada produto.                                                                                 | Estoquista, Gerente                  |
| RF012  | Notificar Validade                    | Alertar sobre produtos com validade próxima ou vencida.                                                                                                        | Estoquista                          |
| RF013  | Manter Cliente                        | Permitir o cadastro de clientes com dados pessoais e de contato, edição e consulta dos dados dos clientes.                                                     | Caixa, Gerente                      |
| RF014  | Registrar Venda                       | Registrar vendas com cliente, usuário, valor total e forma de pagamento, adicionar itens a uma venda com quantidade, valor e subtotal.                         | Caixa                               |
| RF015  | Atualizar Estoque na Venda            | Atualizar o estoque automaticamente ao concluir uma venda.                                                                                                     | Sistema                             |
| RF016  | Controlar Status de Venda             | Controlar o status da venda (concluída, pendente, cancelada).                                                                                                  | Caixa, Gerente                      |
| RF017  | Gerar Contas a Receber                | Gerar contas a receber vinculadas às vendas.                                                                                                                   | Sistema                             |
| RF018  | Gerenciar Contas a Receber            | Permitir registrar pagamento, vencimento e status das contas (pago, pendente, atrasado).                                                                       | Gerente, Financeiro                 |
| RF019  | Registrar Desperdício                 | Registrar desperdícios com data, motivo e quantidade por produto.                                                                                              | Estoquista                          |
| RF020  | Consultar Desperdício                 | Permitir consulta ao histórico de desperdícios por produto.                                                                                                    | Gerente                             |
| RF021  | Gerar Relatórios                      | Permitir geração de relatórios de estoque, vendas e desperdício.                                                                                               | Gerente, Administrador              |
| RF022  | Registrar Ações no Log                | Registrar ações dos usuários, entidade afetada, data e IP de origem.                                                                                           | Sistema                             |
| RF023  | Registrar Lotes                       | Registrar lotes com produto, quantidade, validade, data de entrada e origem.                                                                                   | Estoquista                          |
| RF024  | Rastrear Lote                         | Permitir rastrear produtos por lote no sistema.                                                                                                                | Gerente, Estoquista                  |
| RF025  | Realizar Backup do Sistema            | Permitir realizar backups completos ou incrementais com data, tamanho e status.                                                                                | Administrador                       |
| RF026  | Controlar Perfis                      | Permitir cadastro de perfis de acesso com permissões em JSON.                                                                                                  | Administrador                       |
| RF027  | Atribuir Permissões                   | Atribuir perfis de controle de acesso a usuários.                                                                                                              | Administrador                       |
| RF028  | Registrar Consentimento LGPD          | Permitir registrar consentimento de clientes para tratamento de dados.                                                                                         | Caixa, Gerente                      |
| RF029  | Revogar Consentimento                 | Registrar a revogação do consentimento do cliente.                                                                                                             | Caixa, Gerente                      |
| RF030  | Registrar Solicitações LGPD           | Registrar e controlar solicitações de acesso, correção, exclusão e portabilidade.                                                                              | Cliente, Gerente                    |
| RF031  | Registrar Resposta à Solicitação LGPD | Registrar a resposta à solicitação LGPD, incluindo status e observações.                                                                                       | Gerente, Administrador              |
